version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: forumhub
      MYSQL_ROOT_PASSWORD: careca
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/forumhub?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: careca
      JWT_SECRET: umaSenhaMuitoSecreta123
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    command: ["java", "-jar", "app.jar"]

volumes:
  db_data:
